
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EnviosSOAPService", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8080/comp-cent-web/EnviosSOAP?Wsdl")
public class EnviosSOAPService
    extends Service
{

    private final static URL ENVIOSSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENVIOSSOAPSERVICE_EXCEPTION;
    private final static QName ENVIOSSOAPSERVICE_QNAME = new QName("http://soap/", "EnviosSOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/comp-cent-web/EnviosSOAP?Wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENVIOSSOAPSERVICE_WSDL_LOCATION = url;
        ENVIOSSOAPSERVICE_EXCEPTION = e;
    }

    public EnviosSOAPService() {
        super(__getWsdlLocation(), ENVIOSSOAPSERVICE_QNAME);
    }

    public EnviosSOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENVIOSSOAPSERVICE_QNAME, features);
    }

    public EnviosSOAPService(URL wsdlLocation) {
        super(wsdlLocation, ENVIOSSOAPSERVICE_QNAME);
    }

    public EnviosSOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENVIOSSOAPSERVICE_QNAME, features);
    }

    public EnviosSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnviosSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EnviosSOAP
     */
    @WebEndpoint(name = "EnviosSOAPPort")
    public EnviosSOAP getEnviosSOAPPort() {
        return super.getPort(new QName("http://soap/", "EnviosSOAPPort"), EnviosSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnviosSOAP
     */
    @WebEndpoint(name = "EnviosSOAPPort")
    public EnviosSOAP getEnviosSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "EnviosSOAPPort"), EnviosSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENVIOSSOAPSERVICE_EXCEPTION!= null) {
            throw ENVIOSSOAPSERVICE_EXCEPTION;
        }
        return ENVIOSSOAPSERVICE_WSDL_LOCATION;
    }

}
