
package soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EnviosSOAP", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnviosSOAP {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "cambiarEstadoEnvio", targetNamespace = "http://soap/", className = "soap.CambiarEstadoEnvio")
    @ResponseWrapper(localName = "cambiarEstadoEnvioResponse", targetNamespace = "http://soap/", className = "soap.CambiarEstadoEnvioResponse")
    public void cambiarEstadoEnvio(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        long arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<soap.DtEnvio>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerEnviosPendientesSocioLogistico", targetNamespace = "http://soap/", className = "soap.ObtenerEnviosPendientesSocioLogistico")
    @ResponseWrapper(localName = "obtenerEnviosPendientesSocioLogisticoResponse", targetNamespace = "http://soap/", className = "soap.ObtenerEnviosPendientesSocioLogisticoResponse")
    public List<DtEnvio> obtenerEnviosPendientesSocioLogistico(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
